
<html lang="en">

<head>
    <style>
/*        table{
          position: static;
          top:220px;
          left:200px
        }*/
    </style>
    
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>My life with Nana <3</title>

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="css/bootstrap.min.css" type="text/css">

    <!-- Custom Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="font-awesome/css/font-awesome.min.css" type="text/css">

    <!-- Plugin CSS -->
    <link rel="stylesheet" href="css/animate.min.css" type="text/css">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="css/creative.css" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top">

    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">Welcome to Nana's Heart!<3</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="page-scroll" href="#about">Temperatures and news</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#services">Things to do</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#portfolio">Contact your monster</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact">Grocery List</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    <header>

    <div id="row">
        <div class="col-md-3"></div> 
        <div class="col-md-3" style="top:180px">
            <center>
            <table>
                <!--arrow forward-->
                <tr>
                    <td>
            
                    </td>
                    <td>
                        <a id = "up" href="http://10.0.0.32/?forward">
                            <img src= "img/up.png"width=100px height="80px" align="center"/>
                        </a>
                    </td>
                    <td>
                
                    </td>
                </tr>
              <!-- arrow left -->
              <tr>
                <td>
                  <a id = "left" href="http://10.0.0.32/?left">
                    <img  src= "img/left.png"width="80px" height="100px" align="center"/>
                  </a>
                </td>
                <!-- stop button -->
                <td>
                  <a href="http://10.0.0.32/?stop">
                    <center><img src= "img/pause.png"width="80px" height="80px"/></center>
                  </a>
                </td>
                <!-- arrow right -->
                <td>
                  <a id = "right" href="http://10.0.0.32/?right">
                    <img src= "img/right.png"width="80px" height="100px" align="center"/>
                  </a>
                </td>
              </tr>
              <tr>
                <td>
            
                </td>
                <!-- arrow down -->
                <td>
                  <a id="down" href="http://10.0.0.32/?down">
            
                    <img src= "img/down.png"width=100px height="80px" align="center"/>
                  </a>
                </td>
                <td>
            
                </td>
              </tr>
            </table>
            </center>
            <center>
                <a id="down" href="http://10.0.0.32/?down">
                    <img src= "img/refresh.png"width=120px height="40px" align="center"/>
                </a>
            </center>
        </div>
        <div class="col-md-6" align="right" style="top:150px">
        <iframe class="embed-responsive-item" src="http://10.0.0.41:7777/monitor.asp" height=400 width=100%></iframe>
        </div>
    </div>
    </header>

    <section class="bg-primary" id="about">
        <div class="container">
            <div class="prow">
                <h2 class="section-heading" align="center">This is your home!</h2>
                <hr class="light">
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <img src="img/portfolio/home.jpg" class="img-responsive" alt="" align="center">
                    <!--<a href="#" class="btn btn-default btn-xl"></a>-->
                </div>
                <div class="col-lg-6">
                        </br>
                        <li><h4><strong>Room 1</strong></h4> <h4>Temperature: <?= $_GET["temp"]?> Light: <? echo $GET["light"] ? 'On' : 'Off'?></h4></li>
                        <li><h4><strong>Room 2</strong></h4> <h4>Temperature: <?= $_GET["temp"]?> Light: <? echo $GET["light"] ? 'On' : 'Off'?></h4></li>
                        <li><h4><strong>Room 3</strong></h4> <h4>Temperature: <?= $_GET["temp"]?> Light: <? echo $GET["light"] ? 'On' : 'Off'?></h4></li>
                        <li><h4><strong>Room 4</strong></h4> <h4>Temperature: <?= $_GET["temp"]?> Light: <? echo $GET["light"] ? 'On' : 'Off'?></h4></li>
                        <li><h4><strong>Room 5</strong></h4> <h4>Temperature: <?= $_GET["temp"]?> Light: <? echo $GET["light"] ? 'On' : 'Off'?></h4></li>

                </div>
            </div>
        </div>
    </section>

    <section id="services">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">Well, Happy Sunday!</h2>
                    <hr class="primary">
                    <h4>Things monsters must do today:</h4>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-trash wow bounceIn text-primary"></i>
                        <h3>Stinky!!</h3>
                        <p class="text-muted">Remember to take out the garbage</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-home wow bounceIn text-primary" data-wow-delay=".1s"></i>
                        <h3>Rent is due tomorrow</h3>
                        <p class="text-muted">Remember to submit the check to Linda's account</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-heart wow bounceIn text-primary" data-wow-delay=".3s"></i>
                        <h3>Love and be loved</h3>
                        <p class="text-muted">Remember to smile more today!</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <?php if($_GET["mailbox"] == "true"): ?>
                    <div class="service-box">
                        <i class="fa fa-4x fa-newspaper-o wow bounceIn text-primary" data-wow-delay=".2s"></i>
                        <h3>Up to Date</h3>
                        <p class="text-muted">We have new mail in the mailbox</p>
                    </div>
                    <?php else:?>
                    <div class="service-box">
                    </div>
                    <?php endif;?>
                </div>
            </div>
        </div>
    </section>

    <section class="bg-primary" id="portfolio">
        <div class="row">
            <div class="col-lg-12 text-center">
            <h2 class="section-heading" align="center">Let's get in touch!</h2>
            <hr class="light">
        </div>
        <div class="container-fluid">
            <div class="row no-gutter">
                <div class="col-lg-6" align="center">
                    <a href="#" class="portfolio-box">
                        <img src="img/portfolio/1.jpg" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Missunderstood monster!!
                                </div>
                                <div class="project-name">
                                    Send me a text message<3
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-6" align="center">
                    <a href="#" class="portfolio-box">
                        <img src="img/portfolio/2.jpg" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Missunderstood monster!
                                </div>
                                <div class="project-name">
                                    Send me a text message <3
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </section>
    
    <section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">What about the grocery?</h2>
                    <hr class="primary">
                </div>
            </div>
            <div class=row2>
                <div class="col-lg-4">
                    <h4>Need to add anything to the list?</h4><input type="text"></input>
                </div>
                <div class="col-lg-8">
                    <form action="/controller/ShoppingList.php" method=post>
                        <div class="col-sm-6">
                            <h4><input type="checkbox" name="Bread">Bread</input></h4>
                            <h4><input type="checkbox" name="Apples">Apples</input></h4>
                        </div>
                        <div class="col-sm-6">
                            <h4><input type="checkbox" name="Rice">Rice</input></h4>
                            <h4><input type="checkbox" name="Juice">Juice</input></h4>
                        </div>  
                    </form>
                </div>
            </div>
            </div>
        </div>
    </section>

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="js/jquery.easing.min.js"></script>
    <script src="js/jquery.fittext.js"></script>
    <script src="js/wow.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="js/creative.js"></script>

</body>

</html>
